/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import hexlet.code.App;

import org.junit.jupiter.api.Test;

public class AppTest {
 //  @Test
 //  public void testAppHasAGreeting() {
 //      App classUnderTest = new App();
 //      assertNotNull("app should have a greeting", classUnderTest.getGreeting());
 //  }
}
